### ISSUE TITLE
How to add translated country names?

### ISSUE THREAD

**Issue by szepeviktor** [PrinsFrank/standards#106]
I'd like to add official Hungarian country names
https://cdn.kormany.hu//uploads/sheets//4/4f/4f1/4f1446d8e1badc4b778ff60861cf799.pdf
instead of creating [a new repository](https://github.com/szepeviktor/ISO-3166-orszagnevek-magyarul).

**Comment by PrinsFrank** [comment]
Hi! I'm a bit torn here, because adding a translation for each spec/language combination would mean that the package would increase in size a lot, so I would lean towards an extra package that could optionally be downloaded. We could start a "standards-translation" package. If you want, you can create and maintain that and we can link to it in the readme of this package? Otherwise I could also create it in my name if you would prefer that. Let me know what you think!

**Comment by szepeviktor** [comment]
Could it be that the Netherlands has no committee on geographical names?
https://unstats.un.org/unsd/ungegn/nna/nna-committees/

**Comment by PrinsFrank** [comment]
@szepeviktor I found out that all the country names, language names etc are all already available in the ext-intl package, which is readily available in default PHP installs and already used by the package anyway. Would this work for your use case?: https://github.com/PrinsFrank/standards/pull/116/commits/c4411294e8c2ec7f088d493c548094ca2dc54671

**Comment by szepeviktor** [comment]
Yes. Thank you!!

**Comment by szepeviktor** [comment]
@PrinsFrank It turns out ext-intl contains data from Unicode ICU.
```php
<?php require 'vendor/autoload.php';

use PrinsFrank\Standards\Country\CountryAlpha2;
use PrinsFrank\Standards\Language\LanguageAlpha2;

foreach (CountryAlpha2::cases() as $case) {
    printf("%s\t%s\n", $case->value, $case->getNameInLanguage(LanguageAlpha2::Hungarian));
}
```

**Comment by PrinsFrank** [comment]
@szepeviktor Is that what you expected and can use or is this there something missing there that is available in the other source you mentioned?

**Comment by szepeviktor** [comment]
Here is the difference of official Hungarian names and Unicode ICU/PHP intl:
https://github.com/szepeviktor/ISO-3166-orszagnevek-magyarul/issues/14

**Comment by szepeviktor** [comment]
BTW Have you noticed that ISO 3166 contains short and long names **mixed**?
