### ISSUE TITLE
Kosovo entry missing

### ISSUE THREAD

**Issue by francoisauclair911** [PrinsFrank/standards#270]
Hi,

Could you please add Kosovo (XKX) to the list of countries in your library? While "XKX" is an interim code, it’s currently used by official organizations like the EU and UN. Including it would improve compatibility for applications requiring accurate representation of Kosovo.

Context: https://en.wikipedia.org/wiki/XK_(user_assigned_code)#:~:text=Similarly%2C%20XKX%20is%20an%20ISO,used%20in%20the%20Unicode%20standard.

Thanks!

**Comment by PrinsFrank** [comment]
Hi, Thanks for your suggestion! 

This package is a way to keep an up-to-date list of **official standards** accessible in PHP. It is not its own standard or standard authority. For the CountryAlpha3 standard, this is [maintained by ISO](https://github.com/PrinsFrank/standards/blob/b5a50e3f225f9d7b2a2e009559c6c581896f4e34/src/Country/CountryAlpha3.php#L23) in their [Online Browsing Platform](https://www.iso.org/obp/ui/#search). In fact, this standard is [updated daily from their website](https://github.com/PrinsFrank/standards/blob/b5a50e3f225f9d7b2a2e009559c6c581896f4e34/dev/DataSource/Mapping/CountryMapping.php#L37). 

The code `XKX` (and `XK`) are part of the [`User Assigned Codes` ranges](https://www.iso.org/glossary-for-iso-3166.html), and those don't have a universal meaning, as clarified by ISO in the [glossary for ISO 3166](https://www.iso.org/glossary-for-iso-3166.html);
> Please be advised that the above series of codes are not universal, those code elements are not compatible between different entities.

Therefore, these can't be added to the CountryAlpha3 and CountryAlpha2 enums. I have however just added three methods to check if a code is part of a user assigned space for these two specs (And the CountryNumeric specification) in #271 . 

This package **does** however also contain certain standards that are standards in certain contexts. For example, see the [`Country/UserAssigned` namespace](https://github.com/PrinsFrank/standards/tree/main/src/Country/UserAssigned). This was already requested to be updated - Also for Kosovo - in #261, but the references for that referred to country codes instead of travel documents and a review question was left unanswered. If there are **official** and **universally accepted** authorities that do define these codes for certain domains - like travelDocuments -, I'd be happy to consider them to be included in their own domain-specific standard in the userAssigned namespace.
